# Numpy
* Usado para las listas de python. Arrays
* Array de numpya es el principal objeto
* Se caracteriza por se ordenado y fácil de acceder, esto se da por que
* El array tiene una estructura indexada. Esto quiere decir que tiene encabezados que puede identificar fácilmente cada objeto (elemento) que se encuentra en el array.
* Puede contener millones de datos y
* Accesa a uno o muchos elementos, a grupos de elementos, etc
* Opensource
* A partir de una lista de python, se usa ````np.array([1,2,3]) ````y lo convierte en array

In [3]:
# Libraries
import numpy as np

## Array de 1 dimensión

In [4]:
# definir una lista
lista_1 = [1,2,3,4,5,6,7,8,9]
lista_1

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [7]:
# Convertir la lista a un array con numpy
arr = np.array(lista_1)
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
# Verificar tipo de dato
type(arr)

numpy.ndarray

* Este array es de una dimensión
* Se puede convertir de una a " n" dimensiones

### Aplicar operaciones aritméticas en el array

In [13]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
arr[0] + arr[5]

7

### Como acceder a un elemento

In [11]:
arr[0]

1

### Como acceder a mas de un elemento?
* Aplicando el slicing

In [17]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
# Recuerda que extrae el valor anterior al indice indicado
arr[0:3]

array([1, 2, 3])

In [19]:
arr[2:5]

array([3, 4, 5])

In [20]:
# Sin valor al inicio
arr[:6]

array([1, 2, 3, 4, 5, 6])

In [21]:
#Sin valor al final
arr[2:]

array([3, 4, 5, 6, 7, 8, 9])

In [23]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
# todo de 3 en 3
arr[::3]

array([1, 4, 7])

In [24]:
arr[-1]

9

In [25]:
arr[-3:]

array([7, 8, 9])

## Matriz. Array de dos dimensiones
* Convertir una lista de listas en matriz. Array de dos dimensiones.

In [10]:
matriz = [[1,2,3],[4,5,6],[7,8,9]]
matriz = np.array(matriz)
matriz

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

### Como acceder a los elementos en matrices

* Para extraer elementos de un array se usa el slicing
* Recordar que el indexado comienza por el número "0"

¿Qué pasa al extraer el índice 0 de una matriz?
* Se extrae los elementos de la fila 0 de la matriz

In [26]:
matriz[0]

array([1, 2, 3])

¿Qué pasa al usar dos valores en [a,b]

* El primer valor indica la posición en filas
* El segundo valor indica la posición en columnas
* De esta manera se puede extraer un valor de la matriz

In [16]:
matriz[0,1]

2

### Como acceder a varios elementos en las matrices

In [28]:
matriz[1:]

array([[4, 5, 6],
       [7, 8, 9]])

In [31]:
matriz[:1]

array([[1, 2, 3]])

In [32]:
matriz[-1:]

array([[7, 8, 9]])

In [33]:
matriz[:-1]

array([[1, 2, 3],
       [4, 5, 6]])

In [34]:
matriz[1:,0:2]

array([[4, 5],
       [7, 8]])