# Data Types Numpy
* Un array puede tener solo un tipo de dato
* Un array no puede tener mezclado mas de un tipo de dato
* Los tipos de dato que se pueden manejar: int64, float64, bool, S21 (string)

In [1]:
# Libraries
import numpy as np

## Comandos
* ````np.array```` -> Convierte una lista en array
* ````dtype```` -> Indica el tipo de dato del array. Con una bandera, puede ser usado para convertir de un tipo de dato a otro tipo de dato. Ver In[5]
* ````astype```` -> Sirve para covnertir de un tipo de dato a otro.
* ````np.float64```` -> Junto con astype, convierte de un tipo de dato a float64
* ````no.bool_```` -> Junto con astype, convierte de un tipo de dato a booleano
* ````np.string_```` -> Junto con astype, convierte de un tipo de dato a string
* ````np.int8```` -> Junto con astype, convierte de un tipo de dato a int8

In [6]:
# definir array
arr = np.array([1,2,3,4])
arr

array([1, 2, 3, 4])

In [7]:
# Indicar el tipo de dato
arr.dtype

dtype('int64')

### Maneras de cambiar a otro tipo de dato. 
#### De int64 a float64
* Los número flotantes (decimales) son usados en redes neuronales, tensoflow


In [5]:
# Opción 1
arr2 = np.array([34,45,56], dtype='float64')
arr2.dtype

dtype('float64')

In [8]:
arr2

array([34., 45., 56.])

In [10]:
# Opción 2
arr.astype(np.float64)
arr.dtype

dtype('int64')

#### De int64 a booleano
* En la lógica booleana, el "0" siempre es "False", mientras que los demás números son "True"

In [12]:
arr3 = np.array([0,1,2,3,4,5,6])
arr3 = arr3.astype(np.bool_)
arr3

array([False,  True,  True,  True,  True,  True,  True])

In [13]:
arr3.dtype

dtype('bool')

#### De int64 a string

In [14]:
arr4 = np.array([0,1,2,3,4,5,6])
arr4 = arr4.astype(np.string_)
arr4

array([b'0', b'1', b'2', b'3', b'4', b'5', b'6'], dtype='|S21')

In [15]:
arr4.dtype

dtype('S21')

#### De string a int

In [18]:
arr5 = np.array(['0','1','2','3','4','5','6'])
arr5 = arr5.astype(np.int8)
arr5

array([0, 1, 2, 3, 4, 5, 6], dtype=int8)

In [19]:
arr5.dtype

dtype('int8')

#### invalid literal for int() with base 10:
* Un texto no puede convertirse a entero

In [20]:
arr6 = np.array(['hola','1','2','3','4','5','6'])
arr6 = arr6.astype(np.int8)
arr6

ValueError: invalid literal for int() with base 10: 'hola'

## Tipos de datos que maneja Numpy
[Tipos de Datos](https://numpy.org/doc/stable/user/basics.types.html)