# Formas de crear arrays

In [1]:
# Libraries
import numpy as np

## Comandos para crear arrays
* np.arange
* np.zeros -> Se usa para definir estructuras
* np.ones -> Se usa para definir estructuras
* np linspace ->
* np.eye ->
* np.random.rand()
* np.random.randint

In [2]:
#1 Lista de Python
list(range(0,10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [6]:
#1 
np.arange(0,15,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14])

In [8]:
np.zeros((10,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [9]:
np.ones((10,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [11]:
np.linspace(0,10,100) # crea un array de 100 elementos de 0 a 10

array([ 0.        ,  0.1010101 ,  0.2020202 ,  0.3030303 ,  0.4040404 ,
        0.50505051,  0.60606061,  0.70707071,  0.80808081,  0.90909091,
        1.01010101,  1.11111111,  1.21212121,  1.31313131,  1.41414141,
        1.51515152,  1.61616162,  1.71717172,  1.81818182,  1.91919192,
        2.02020202,  2.12121212,  2.22222222,  2.32323232,  2.42424242,
        2.52525253,  2.62626263,  2.72727273,  2.82828283,  2.92929293,
        3.03030303,  3.13131313,  3.23232323,  3.33333333,  3.43434343,
        3.53535354,  3.63636364,  3.73737374,  3.83838384,  3.93939394,
        4.04040404,  4.14141414,  4.24242424,  4.34343434,  4.44444444,
        4.54545455,  4.64646465,  4.74747475,  4.84848485,  4.94949495,
        5.05050505,  5.15151515,  5.25252525,  5.35353535,  5.45454545,
        5.55555556,  5.65656566,  5.75757576,  5.85858586,  5.95959596,
        6.06060606,  6.16161616,  6.26262626,  6.36363636,  6.46464646,
        6.56565657,  6.66666667,  6.76767677,  6.86868687,  6.96

In [12]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [14]:
# generar numeros aleatorios
np.random.rand()

0.3146556357631727

In [15]:
np.random.rand(4)

array([0.70326301, 0.98687531, 0.5608296 , 0.32598257])

In [16]:
np.random.rand(4,4)

array([[0.16866429, 0.69633527, 0.51082251, 0.85108178],
       [0.27421372, 0.56872016, 0.07518448, 0.47166749],
       [0.99366615, 0.02866835, 0.41165892, 0.38732908],
       [0.09534589, 0.71240049, 0.52197447, 0.13284859]])

In [17]:
np.random.randint(1,15)

9

In [18]:
np.random.randint(1,100,(10,10))

array([[32, 23, 86,  6, 97, 75, 34, 22,  5, 16],
       [37,  1,  6, 19, 36,  9, 70, 48, 79, 69],
       [76,  3, 91,  9, 77, 51, 45, 51,  2, 12],
       [43, 28, 87, 33, 46, 59, 50,  6, 28, 56],
       [14, 59, 85,  6, 24, 99, 58, 60, 75, 48],
       [76, 27, 36,  6, 68, 70, 22, 72, 74,  5],
       [ 8, 88, 47, 26, 22, 48, 39, 77, 51,  4],
       [17, 95, 45, 67, 51, 43, 96, 31, 92, 37],
       [94, 60, 15, 13, 34, 73, 35,  1, 43, 50],
       [75, 73, 40, 99, 56,  5, 80, 14, 73,  9]])