In [2]:
# Libraries
import numpy as np

# Shape y Reshape

## Comandos
1. shape
2. reshape

In [4]:
# generar un array
arr = np.random.randint(1,10,(3,2))
arr

array([[2, 4],
       [3, 8],
       [3, 3]])

In [5]:
arr.shape

(3, 2)

In [7]:
arr.reshape(6,1)

array([[2],
       [4],
       [3],
       [8],
       [3],
       [3]])

In [8]:
arr.reshape(1,6)

array([[2, 4, 3, 8, 3, 3]])

In [9]:
arr.reshape(2,3)

array([[2, 4, 3],
       [8, 3, 3]])

In [10]:
# otra forma
np.reshape(arr,(1,6))

array([[2, 4, 3, 8, 3, 3]])

In [13]:
# como ordena al ejecutar reshape?
np.reshape(arr,(2,3),'c') # ordenamiento del lenguaje C

array([[2, 4, 3],
       [8, 3, 3]])

In [14]:
np.reshape(arr,(2,3),'f') # ordenamiento del lenguaje Fortland

array([[2, 3, 8],
       [3, 4, 3]])

In [15]:
np.reshape(arr,(2,3),'a') # ordenamiento optimizado de mi sistema (MACOS)

array([[2, 4, 3],
       [8, 3, 3]])