# Funciones principales

In [1]:
# Libraries
import numpy as np

## Comandos
* max()
* argmax() -> retorna el índice del array donde se encuentra el valor máximo
* min()
* argmin()
* ptp (peek to peek) -> retorna la diferencia entre el valor máximo y el valor mínimo
* percentile -> Retorna 

In [5]:
# Crear arrary con valores int aleatorios
arr = np.random.randint(1,20,10)
arr

array([ 7, 17,  9, 14,  9, 18,  2,  5, 13,  3])

In [6]:
# Usar la función max()
arr.max()

18

In [10]:
arr.argmax()

5

In [4]:
# Crear una matriz
matriz = arr.reshape(2,5)
matriz

array([[ 2, 10,  9,  7, 14],
       [16, 11,  7, 11, 11]])

In [7]:
# Usar max() en una matriz
matriz.max()

16

In [8]:
# Usar max() en filas
matriz.max(1)

array([14, 16])

In [9]:
# Usar max() en lkas columnas
matriz.max(0)

array([16, 11,  9, 11, 14])

In [11]:
# Usar argmax() en la matriz
matriz.argmax()

5

In [ ]:
# Completar ejercicios con min() y argmin()

In [14]:
print(arr.min())
print(arr.max())
arr.ptp()

2
18


16

In [16]:
#ptp usado en matriz
print(matriz.min())
print(matriz.max())
matriz.ptp()

2
16


14