# Funciones principales

In [1]:
# Libraries
import numpy as np

## Comandos
* max()
* argmax() -> retorna el índice del array donde se encuentra el valor máximo
* min()
* argmin()
* ptp (peek to peek) -> retorna la diferencia entre el valor máximo y el valor mínimo
* percentile -> Retorna los percentiles de un array 
* sort() -> ordena los valores de un array
* np.mean( )
* np.median( )
* np.std( )
* np.var( )
* np.concatenate( )

In [5]:
# Crear arrary con valores int aleatorios
arr = np.random.randint(1,20,10)
arr

array([ 7, 17,  9, 14,  9, 18,  2,  5, 13,  3])

In [6]:
# Usar la función max()
arr.max()

18

In [10]:
arr.argmax()

5

In [4]:
# Crear una matriz
matriz = arr.reshape(2,5)
matriz

array([[ 2, 10,  9,  7, 14],
       [16, 11,  7, 11, 11]])

In [7]:
# Usar max() en una matriz
matriz.max()

16

In [8]:
# Usar max() en filas
matriz.max(1)

array([14, 16])

In [9]:
# Usar max() en lkas columnas
matriz.max(0)

array([16, 11,  9, 11, 14])

In [11]:
# Usar argmax() en la matriz
matriz.argmax()

5

In [ ]:
# Completar ejercicios con min() y argmin()

In [14]:
print(arr.min())
print(arr.max())
arr.ptp()

2
18


16

In [16]:
#ptp usado en matriz
print(matriz.min())
print(matriz.max())
matriz.ptp()

2
16


14

### np.percentile( x )
* En 50, retorna el valor que se encuentra en la mitad o bien el promedio de los valores que se encuentran en medio del array

In [18]:
arr

array([ 7, 17,  9, 14,  9, 18,  2,  5, 13,  3])

In [17]:
# usando percentile en el array
np.percentile(arr,50) 

9.0

In [19]:
np.percentile(arr,0) # retorna el valor mas bajo

2.0

In [20]:
np.percentile(arr,100) # retorna el valor más alto

18.0

In [22]:
np.percentile(arr,25) # retorna el valor que esta entre el mas bajo y la mitad

5.5

In [25]:
# ordena los elementos de un array
arr.sort()
arr

array([ 2,  3,  5,  7,  9,  9, 13, 14, 17, 18])

### np.mean( )

In [37]:
np.mean(arr)

9.7

In [36]:
np.mean(matriz)

9.8

### np.median( )
* Retorna la medina de un arreglo

In [26]:
# aplicado en el array
np.median(arr)

9.0

In [27]:
# aplicado en la matriz
np.median(matriz) # retorna 

10.5

In [28]:
np.median(matriz,1) # retorna la mediana de cada fila

array([ 9., 11.])

In [29]:
np.median(matriz,0) # retorna la mediana de cada columna

array([ 9. , 10.5,  8. ,  9. , 12.5])

# np.std( )
* Retorna la desviación estandar del array

In [30]:
np.std(arr)

5.348831648126533

In [31]:
np.std(matriz)

3.7094473981982814

In [32]:
np.std(arr)**2

28.61

In [33]:
np.var(arr)

28.610000000000003

### np.concatenate((a,b),axis=0)

In [38]:
brr = np.random.randint(1,20,10)

In [39]:
brr

array([ 7,  7, 12, 18,  1, 19, 17, 17, 17, 19])

In [41]:
new_one = np.concatenate((arr,brr),axis=0) # concatenar por 

In [42]:
new_one

array([ 2,  3,  5,  7,  9,  9, 13, 14, 17, 18,  7,  7, 12, 18,  1, 19, 17,
       17, 17, 19])

In [43]:
new_two = np.concatenate((arr,brr),axis=1)

AxisError: axis 1 is out of bounds for array of dimension 1

In [ ]:
new_two