# Comando **copy**
* Crea una copia del array
* array.copy()

In [1]:
# Libraries
import numpy as np

In [12]:
# Crear una array
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [13]:
#Extraer los elementos de las posicion de la 0 a la 6
pedazo_de_arr = arr[0:6]

In [7]:
pedazo_de_arr

array([0, 1, 2, 3, 4, 5])

In [8]:
# cambiar los valores de pedazo_de_arr a cero 0
pedazo_de_arr[:] = 0
pedazo_de_arr

array([0, 0, 0, 0, 0, 0])

In [9]:
arr

array([ 0,  0,  0,  0,  0,  0,  6,  7,  8,  9, 10])

In [ ]:
# Crear nuevo array

In [19]:
arr1 = np.arange(0,15)
arr1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [20]:
# Crear copia del array
arr_copy = arr1.copy()
arr_copy

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [21]:
pedacito = arr_copy[0:6]
pedacito

array([0, 1, 2, 3, 4, 5])

In [22]:
pedacito[:] = 1
pedacito

array([1, 1, 1, 1, 1, 1])

In [23]:
arr1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [24]:
arr_copy

array([ 1,  1,  1,  1,  1,  1,  6,  7,  8,  9, 10, 11, 12, 13, 14])