# Condiciones

In [1]:
# Libraries
import numpy as np

In [2]:
arr = np.linspace(1,10,10,dtype='int8')
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10], dtype=int8)

In [3]:
arr < 5

array([ True,  True,  True,  True, False, False, False, False, False,
       False])

In [4]:
menores_a_5 = arr < 5

In [5]:
menores_a_5

array([ True,  True,  True,  True, False, False, False, False, False,
       False])

In [6]:
arr[menores_a_5]

array([1, 2, 3, 4], dtype=int8)

In [7]:
# otra opción que hace lo mismo al anterior
arr[arr<5]

array([1, 2, 3, 4], dtype=int8)

In [8]:
# Multiples condiciones
arr[(arr>5)&(arr<9)]

array([6, 7, 8], dtype=int8)